stages:
  - build

variables:
  CONTAINER_STAGING_IMAGE: registry.arcdev.ru/arcsinus/postgres:11

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.arcdev.ru

build_develop:
  stage: build
  tags:
    - dockerhttp
  script:
    - docker build -t $CONTAINER_STAGING_IMAGE .
    - docker push $CONTAINER_STAGING_IMAGE

